FROM ubuntu:24.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY . /app/
RUN pip3 install -r requirements.txt --break-system-packages
CMD ["python3", "bot.py"]